version: 2
updates:
  - package-ecosystem: "poetry"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      python-package-updates:
        patterns:
          - ".*"
        group-name: "All Python package updates"